[package]
name = "folder_locker"
version = "0.1.0"
edition = "2021"

[dependencies]
bcrypt = "0.15.1"
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
dialoguer = "0.11.0"
winapi = { version = "0.3.9", features = ["fileapi", "winnt"] }
